/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ugallery;
import static com.mycompany.ugallery.InicioJFrame.nombreUsTxt;
import estructuras.ListaDobleImagen;
import java.awt.Image;
import java.awt.List;
import java.io.File;
import java.util.ArrayList;
        
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author josse
 */
public class BibliotecaJFrame extends javax.swing.JFrame {
     public String datoUsuario;
     DefaultListModel modeloCategoria = new DefaultListModel();
    
    /**
     * Creates new form BibliotecaJFrame
     */
    public BibliotecaJFrame() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("BIBLIOTECA");
        
        categoriaList.setModel(modeloCategoria);
        rutaImagenTxt.setVisible(false);
        nombreImagenTxt.setVisible(false);
        
        datoUsuario = nombreUsTxt.getText();
        System.out.println(datoUsuario);
        
        Usuario usuarioActual = (Usuario) AppState.listausuarios.find(datoUsuario);
        
        DefaultListModel<String> model = new DefaultListModel<String>();
        ArrayList<Categoria> categorias = usuarioActual.getListaCategorias();
        for (Categoria categoria : categorias) {
            model.addElement(categoria.getNombreCategoria());
        }
        categoriaList.setModel(model);

     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoriaList = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        imagenLbl = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        nombreCategoriaTxt = new javax.swing.JTextField();
        UsuarioTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rutaImagenTxt = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        contadorLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contadortotal = new javax.swing.JLabel();
        nombreImagenTxt = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 54, 60));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(154, 185, 152));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGRESAR ");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(154, 185, 152)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categorías");

        categoriaList.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        categoriaList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriaListMouseClicked(evt);
            }
        });
        categoriaList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                categoriaListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(categoriaList);

        jButton2.setBackground(new java.awt.Color(235, 73, 96));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(235, 73, 96));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText(">");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(254, 206, 170));

        imagenLbl.setBackground(new java.awt.Color(254, 206, 170));
        imagenLbl.setText("AQUI ESTARÁ LA IMAGEN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(imagenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setBackground(new java.awt.Color(235, 73, 96));
        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Agregar Imagen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(235, 73, 96));
        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Eliminar Imagen");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(235, 73, 96));
        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Agregar Categoría");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        nombreCategoriaTxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        UsuarioTxt.setBackground(new java.awt.Color(41, 54, 60));
        UsuarioTxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        UsuarioTxt.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioTxt.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");

        jButton8.setBackground(new java.awt.Color(235, 73, 96));
        jButton8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Seleccionar Imagen");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FOTOGRAFÍA");

        contadorLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        contadorLbl.setForeground(new java.awt.Color(255, 255, 255));
        contadorLbl.setText("0");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("/");

        contadortotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        contadortotal.setForeground(new java.awt.Color(255, 255, 255));
        contadortotal.setText("0");

        jButton9.setBackground(new java.awt.Color(235, 73, 96));
        jButton9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Eliminar categoría");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rutaImagenTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                            .addComponent(nombreImagenTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UsuarioTxt))
                            .addComponent(nombreCategoriaTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(170, 170, 170)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(contadorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contadortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(contadorLbl)
                            .addComponent(jLabel5)
                            .addComponent(contadortotal))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nombreCategoriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rutaImagenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreImagenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InicioJFrame pr = new InicioJFrame();
        pr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(nombreImagenTxt.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Selecciona una categoría para eliminar la imagen.", "Ugallery", JOptionPane.ERROR_MESSAGE);
        }else{
            Usuario usuarioActual = (Usuario) AppState.listausuarios.find(UsuarioTxt.getText()); 
            Categoria categoria = (Categoria)usuarioActual.listacategoria.get(categoriaList.getSelectedIndex());
            categoria.getListaimagenes().delete(nombreImagenTxt.getText());
            JOptionPane.showMessageDialog(null, "Imagen Eliminada Correctamente", "Ugallery", JOptionPane.INFORMATION_MESSAGE);
            categoria.ImprimirImagenes();
            nombreImagenTxt.setText(null);
            imagenLbl.setIcon(null);   
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Usuario usuarioAct = (Usuario)AppState.listausuarios.find(UsuarioTxt.getText());
        int selectedIndex = categoriaList.getSelectedIndex();
        if (rutaImagenTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Imagen", "IMAGEN", JOptionPane.WARNING_MESSAGE);
        } else if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una categoría.", "CATEGORÍA", JOptionPane.WARNING_MESSAGE);
        } else {
            File archivo = new File(rutaImagenTxt.getText());
            String fileName=archivo.getName();

            String nombre = FilenameUtils.getBaseName(fileName);
            ImageIcon imagen = new ImageIcon(rutaImagenTxt.getText());
            Imagen nuevaImagen = new Imagen();
            nuevaImagen.setImageIcon(imagen);
            nuevaImagen.setNombre(nombre);
            nuevaImagen.setRutaImagen(rutaImagenTxt.getText());

            Categoria categoria = (Categoria)usuarioAct.getListaCategorias().get(categoriaList.getSelectedIndex());
            categoria.agregarImagen(nuevaImagen);

            JOptionPane.showMessageDialog(null, "Imagen agregada correctamente a la categoría: "+categoriaList.getSelectedValue(), "Ugallery", JOptionPane.INFORMATION_MESSAGE); 
            categoria.ImprimirImagenes();
            System.out.println("----------------------------------------------");

            rutaImagenTxt.setText(null);
            nombreImagenTxt.setText(null);
            imagenLbl.setIcon(null);
        }
        
        
        
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Usuario usuarioActual = (Usuario) AppState.listausuarios.find(UsuarioTxt.getText()); 
        Categoria categoria = (Categoria)usuarioActual.listacategoria.get(categoriaList.getSelectedIndex());
        if(nombreImagenTxt.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Selecciona una categoría para cambiar de imagen.", "Ugallery", JOptionPane.ERROR_MESSAGE);
        }else{
           categoria.SiguienteImagen(nombreImagenTxt, imagenLbl,contadorLbl);

        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

       String nombreCat = nombreCategoriaTxt.getText();
       Usuario usuarioActual = (Usuario) AppState.listausuarios.find(UsuarioTxt.getText());
       boolean categoriaExiste = false;

       Categoria addCategoria = new Categoria();


        // Validar que se haya ingresado un nombre de categoría
        if (nombreCat.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre de la categoría", "CAMPO VACÍO", JOptionPane.WARNING_MESSAGE);
        } else {
            for (Categoria categoria : usuarioActual.getListaCategorias()) {
                if (categoria.getNombreCategoria().equals(nombreCat)) {
                    categoriaExiste = true;
                    break;
                }
            }

            if (categoriaExiste) {
                JOptionPane.showMessageDialog(null, "Ya existe una categoría con ese nombre para este usuario", "CATEGORÍA DUPLICADA", JOptionPane.WARNING_MESSAGE);
            } else {
                addCategoria.setNombreCategoria(nombreCat);
                usuarioActual.agregarCategoria(addCategoria);
                JOptionPane.showMessageDialog(null, "Categoría agregada correctamente", "CATEGORÍA", JOptionPane.INFORMATION_MESSAGE);
                DefaultListModel<String> model = null;
                if (categoriaList.getModel() == null) {
                    model = new DefaultListModel<String>();
                    categoriaList.setModel(model);
                } else {
                    model = (DefaultListModel<String>) categoriaList.getModel();
                }

                model.addElement(addCategoria.getNombreCategoria());
                nombreCategoriaTxt.setText(null);
            }
        } 
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JFileChooser archivo = new JFileChooser();
        FileFilter filtro1 = new FileNameExtensionFilter("JPG", "jpg");
        archivo.setFileFilter(filtro1);
        int ventana= archivo.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION){
            File file= archivo.getSelectedFile();
            rutaImagenTxt.setText(String.valueOf(file));
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Usuario usuarioActual = (Usuario) AppState.listausuarios.find(UsuarioTxt.getText()); 
        Categoria categoria = (Categoria)usuarioActual.listacategoria.get(categoriaList.getSelectedIndex());
        if(nombreImagenTxt.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Selecciona una categoría para cambiar de imagen.", "Ugallery", JOptionPane.ERROR_MESSAGE);
        }else{
           categoria.AnteriorImagen(nombreImagenTxt, imagenLbl, contadorLbl);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void categoriaListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaListMouseClicked
        Usuario usuarioActual = (Usuario) AppState.listausuarios.find(UsuarioTxt.getText()); 
        Categoria categoria = (Categoria)usuarioActual.listacategoria.get(categoriaList.getSelectedIndex());
        String NombreImagen;
        if(categoria!=null) {
            ListaDobleImagen listaImagenes = categoria.getListaimagenes();
            if (listaImagenes.get(0)!=null) {
                Imagen iconImagen = (Imagen) listaImagenes.get(0);
                NombreImagen =iconImagen.nombre;
                ImageIcon iconoImagen = iconImagen.getImageIcon();
                Image Imagen = iconoImagen.getImage();
                Imagen = Imagen.getScaledInstance(imagenLbl.getWidth(), imagenLbl.getHeight(), Image.SCALE_DEFAULT);
                imagenLbl.setIcon(new ImageIcon(Imagen));
                nombreImagenTxt.setText(NombreImagen);
                contadorLbl.setText("1");
                contadortotal.setText(String.valueOf(listaImagenes.getSize()));
                
                
            }else{
                
                contadorLbl.setText("0");
                contadortotal.setText("0");
                nombreImagenTxt.setText(null);
                imagenLbl.setIcon(null); 
            }
        }
    }//GEN-LAST:event_categoriaListMouseClicked

    private void categoriaListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_categoriaListValueChanged


    }//GEN-LAST:event_categoriaListValueChanged

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String nombreUs = UsuarioTxt.getText();
        Usuario usuarioActual = (Usuario) AppState.listausuarios.find(nombreUs);

        // Validar que se haya seleccionado una categoría
        int index = categoriaList.getSelectedIndex();
        if (index >= 0) {
            String nombreCat = categoriaList.getModel().getElementAt(index);
            Categoria categoriaSeleccionada = usuarioActual.buscarCategoria(nombreCat);
            if (categoriaSeleccionada == null) {
                JOptionPane.showMessageDialog(null, "La categoría no existe para este usuario", "CATEGORÍA NO ENCONTRADA", JOptionPane.WARNING_MESSAGE);
            } else {
                // Eliminar todas las imágenes de la categoría
                usuarioActual.eliminarCategoria(categoriaSeleccionada);
                ListaDobleImagen listaImagenes = categoriaSeleccionada.getListaimagenes();
                listaImagenes.clear();

                // Actualizar el JList de categorías
                ArrayList<Categoria> categorias = usuarioActual.getListaCategorias();
                if (!categorias.isEmpty()) {
                    DefaultListModel<String> model = new DefaultListModel<>();
                    for (Categoria categoria : categorias) {
                        model.addElement(categoria.getNombreCategoria());
                    }
                    categoriaList.setModel(model);
                    categoriaList.setSelectedIndex(0); // Seleccionar la primera categoría de la lista
                } else {
                    DefaultListModel<String> model = new DefaultListModel<>();
                    categoriaList.setModel(model);
                }
                
                JOptionPane.showMessageDialog(null, "Categoría eliminada correctamente", "CATEGORÍA", JOptionPane.INFORMATION_MESSAGE);
                 imagenLbl.setIcon(null);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una categoría", "CATEGORÍA NO SELECCIONADA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotecaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotecaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotecaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BibliotecaJFrame().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField UsuarioTxt;
    private javax.swing.JList<String> categoriaList;
    private javax.swing.JLabel contadorLbl;
    private javax.swing.JLabel contadortotal;
    private javax.swing.JLabel imagenLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreCategoriaTxt;
    private javax.swing.JTextField nombreImagenTxt;
    private javax.swing.JTextField rutaImagenTxt;
    // End of variables declaration//GEN-END:variables
}
